### ISSUE TITLE
Heroku URL not responding

### ISSUE THREAD

**Issue by cpursley** [tech404/inviter#2]
https://tech404-inviter.herokuapp.com/

http://awesomescreenshot.com/0504e146dc

**Comment by alindeman** [comment]
Heya! This is intentional. There is no page served up at https://tech404-inviter.herokuapp.com/. This is a JSON API only. The only route that does respond is documented in the README.

If you want to sign up for the organization, see http://tech404.io

Hope that clears things up. If you have any more questions, let me know.
